# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from pydantic import BaseModel, Field
from typing import List, Optional

from typing_extensions import Literal

__all__ = ["ChatCompletionContentPartRefusalParam"]


class ChatCompletionContentPartRefusalParam(BaseModel):
    refusal: "str"= None
    
    """The refusal message generated by the model."""

    type: "Literal['refusal']"= None
    
    """The type of the content part."""
ChatCompletionContentPartRefusalParam.model_rebuild()

