# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from pydantic import BaseModel, Field
from typing import List, Optional

from typing import Union,Optional,List
from typing_extensions import Literal

from ..shared_params.metadata import Metadata
from .code_interpreter_tool_param import CodeInterpreterToolParam
from .threads.message_content_part_param import MessageContentPartParam

__all__ = [
    "ThreadCreateParams",
    "Message",
    "MessageAttachment",
    "MessageAttachmentTool",
    "MessageAttachmentToolFileSearch",
    "ToolResources",
    "ToolResourcesCodeInterpreter",
    "ToolResourcesFileSearch",
    "ToolResourcesFileSearchVectorStore",
    "ToolResourcesFileSearchVectorStoreChunkingStrategy",
    "ToolResourcesFileSearchVectorStoreChunkingStrategyAuto",
    "ToolResourcesFileSearchVectorStoreChunkingStrategyStatic",
    "ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic",
]


class ThreadCreateParams(BaseModel):
    messages: "Optional[List[Message]]"=Field(default_factory=list)
    
    """
    A list of [messages](https://platform.openai.com/docs/api-reference/messages) to
    start the thread with.
    """

    metadata: "Optional[Metadata]"= None
    
    """Set of 16 key-value pairs that can be attached to an object.

    This can be useful for storing additional information about the object in a
    structured format, and querying for objects via API or the dashboard.

    Keys are strings with a maximum length of 64 characters. Values are strings with
    a maximum length of 512 characters.
    """

    tool_resources: "Optional[ToolResources]"= None
    
    """
    A set of resources that are made available to the assistant's tools in this
    thread. The resources are specific to the type of tool. For example, the
    `code_interpreter` tool requires a list of file IDs, while the `file_search`
    tool requires a list of vector store IDs.
    """


class MessageAttachmentToolFileSearch(BaseModel):
    type: "Literal['file_search']"
    
    """The type of tool being defined: `file_search`"""


MessageAttachmentTool = Union[CodeInterpreterToolParam, MessageAttachmentToolFileSearch]


class MessageAttachment(BaseModel):
    file_id: "Optional[str]"= None
    
    """The ID of the file to attach to the message."""

    tools: "Optional[List[MessageAttachmentTool]]"=Field(default_factory=list)
    
    """The tools to add this file to."""


class Message(BaseModel):
    content: "Union[str, List[MessageContentPartParam]]"
    
    """The text contents of the message."""

    role: "Literal['user', 'assistant']"
    
    """The role of the entity that is creating the message. Allowed values include:

    - `user`: Indicates the message is sent by an actual user and should be used in
      most cases to represent user-generated messages.
    - `assistant`: Indicates the message is generated by the assistant. Use this
      value to insert messages from the assistant into the conversation.
    """

    attachments: "Optional[List[MessageAttachment]]"=Field(default_factory=list)
    
    """A list of files attached to the message, and the tools they should be added to."""

    metadata: "Optional[Metadata]"= None
    
    """Set of 16 key-value pairs that can be attached to an object.

    This can be useful for storing additional information about the object in a
    structured format, and querying for objects via API or the dashboard.

    Keys are strings with a maximum length of 64 characters. Values are strings with
    a maximum length of 512 characters.
    """


class ToolResourcesCodeInterpreter(BaseModel):
    file_ids: "Optional[List[str]]"= None
    
    """
    A list of [file](https://platform.openai.com/docs/api-reference/files) IDs made
    available to the `code_interpreter` tool. There can be a maximum of 20 files
    associated with the tool.
    """


class ToolResourcesFileSearchVectorStoreChunkingStrategyAuto(BaseModel):
    type: "Literal['auto']"
    
    """Always `auto`."""


class ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic(BaseModel):
    chunk_overlap_tokens: "int"
    
    """The number of tokens that overlap between chunks. The default value is `400`.

    Note that the overlap must not exceed half of `max_chunk_size_tokens`.
    """

    max_chunk_size_tokens: "int"
    
    """The maximum number of tokens in each chunk.

    The default value is `800`. The minimum value is `100` and the maximum value is
    `4096`.
    """


class ToolResourcesFileSearchVectorStoreChunkingStrategyStatic(BaseModel):
    static: "ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic"
    

    type: "Literal['static']"
    
    """Always `static`."""


ToolResourcesFileSearchVectorStoreChunkingStrategy = Union[
    ToolResourcesFileSearchVectorStoreChunkingStrategyAuto, ToolResourcesFileSearchVectorStoreChunkingStrategyStatic
]


class ToolResourcesFileSearchVectorStore(BaseModel):
    chunking_strategy: "Optional[ToolResourcesFileSearchVectorStoreChunkingStrategy]"= None
    
    """The chunking strategy used to chunk the file(s).

    If not set, will use the `auto` strategy.
    """

    file_ids: "Optional[List[str]]"= None
    
    """
    A list of [file](https://platform.openai.com/docs/api-reference/files) IDs to
    add to the vector store. There can be a maximum of 10000 files in a vector
    store.
    """

    metadata: "Optional[Metadata]"= None
    
    """Set of 16 key-value pairs that can be attached to an object.

    This can be useful for storing additional information about the object in a
    structured format, and querying for objects via API or the dashboard.

    Keys are strings with a maximum length of 64 characters. Values are strings with
    a maximum length of 512 characters.
    """


class ToolResourcesFileSearch(BaseModel):
    vector_store_ids: "Optional[List[str]]"= None
    
    """
    The
    [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object)
    attached to this thread. There can be a maximum of 1 vector store attached to
    the thread.
    """

    vector_stores: "Optional[List[ToolResourcesFileSearchVectorStore]]"=Field(default_factory=list)
    
    """
    A helper to create a
    [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object)
    with file_ids and attach it to this thread. There can be a maximum of 1 vector
    store attached to the thread.
    """


class ToolResources(BaseModel):
    code_interpreter: "Optional[ToolResourcesCodeInterpreter]"= None
    

    file_search: "Optional[ToolResourcesFileSearch]"= None
    
ThreadCreateParams.model_rebuild()
MessageAttachmentToolFileSearch.model_rebuild()
MessageAttachment.model_rebuild()
Message.model_rebuild()
ToolResourcesCodeInterpreter.model_rebuild()
ToolResourcesFileSearchVectorStoreChunkingStrategyAuto.model_rebuild()
ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic.model_rebuild()
ToolResourcesFileSearchVectorStoreChunkingStrategyStatic.model_rebuild()
ToolResourcesFileSearchVectorStore.model_rebuild()
ToolResourcesFileSearch.model_rebuild()
ToolResources.model_rebuild()

