# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from pydantic import BaseModel, Field
from typing import List, Optional

from typing import Union,Optional
from typing_extensions import Literal

from ...shared_params.metadata import Metadata
from .message_content_part_param import MessageContentPartParam
from ..code_interpreter_tool_param import CodeInterpreterToolParam

__all__ = ["MessageCreateParams", "Attachment", "AttachmentTool", "AttachmentToolFileSearch"]


class MessageCreateParams(BaseModel):
    content: "Union[str, List[MessageContentPartParam]]"
    
    """The text contents of the message."""

    role: "Literal['user', 'assistant']"
    
    """The role of the entity that is creating the message. Allowed values include:

    - `user`: Indicates the message is sent by an actual user and should be used in
      most cases to represent user-generated messages.
    - `assistant`: Indicates the message is generated by the assistant. Use this
      value to insert messages from the assistant into the conversation.
    """

    attachments: "Optional[List[Attachment]]"=Field(default_factory=list)
    
    """A list of files attached to the message, and the tools they should be added to."""

    metadata: "Optional[Metadata]"= None
    
    """Set of 16 key-value pairs that can be attached to an object.

    This can be useful for storing additional information about the object in a
    structured format, and querying for objects via API or the dashboard.

    Keys are strings with a maximum length of 64 characters. Values are strings with
    a maximum length of 512 characters.
    """


class AttachmentToolFileSearch(BaseModel):
    type: "Literal['file_search']"
    
    """The type of tool being defined: `file_search`"""


AttachmentTool = Union[CodeInterpreterToolParam, AttachmentToolFileSearch]


class Attachment(BaseModel):
    file_id: "Optional[str]"= None
    
    """The ID of the file to attach to the message."""

    tools: "Optional[List[AttachmentTool]]"=Field(default_factory=list)
    
    """The tools to add this file to."""
MessageCreateParams.model_rebuild()
AttachmentToolFileSearch.model_rebuild()
Attachment.model_rebuild()

